### PR TITLE
QOLOE-171 Typography New QA Branch

### PR DESCRIPTION
**Pull request by tedqgov**
QA issue: https://ssq-qol.atlassian.net/browse/QOLOE-171

### CODE REVIEW

**Comment by tedqgov** [comment]
@re-becca I'm adding the visited-link text decoration color back in now -- Had to start a new branch to cherry pick. My storybook can't run locally anymore so I had to commit my changes first

**Comment by tedqgov** [comment]
@re-becca Changes are done :) Apologies for taking so long

**Comment by duttonw** [comment]
need to resolve conflicts.

**Comment by duttonw** [comment]
Hi @tedqgov ,
Can you review this PR, I've done a  ``git pull origin develop --rebase `` and fixed all the merge conflicts as well as stripped all of the extra bits which you were not working on.

There was a major conflict around qld-type.scss caption that I need to to reverify that it is indeed needed.

Regards,

@duttonw 

cc: @stvp-qld  you may want to double review also.

**Review by duttonw — APPROVED** [review]

**Pull request merged**
