### PR TITLE
QOLOE-190 Search Input QA

### PR DESCRIPTION
**Pull request by tedqgov**
Design QA Ticket: https://ssq-qol.atlassian.net/browse/QOLOE-190

### CODE REVIEW

**Review by elvishu — DISMISSED** [review]
Code looks good. Approve to allow merge for Design review.

**Review by duttonw — DISMISSED** [review]

**Review by MitchAnderson93 — CHANGES_REQUESTED** [review]

**Comment by duttonw** [comment]
Hi @tedqgov ,

I've rebased this work to clear the merge conflict and make the history much easier to read. Please double check I did not lose anything you wanted included. 

Also please make the requested changes to REM instead of PX so that the screen magnify (a11y) does not break things unexpectedly. Please see: https://dev.to/ochukodotspace/the-battle-of-the-units-px-vs-rem-vs-em-3ka8

Regards,

@duttonw

**Comment by tedqgov** [comment]
Sorry, been overwhelmed by ticket emails and missed this - will get onto it now

**Comment by tedqgov** [comment]
Starting new branch due to rebasing issue.

**Comment by tedqgov** [comment]
I just merged develop branch changes to search-input branch, instead of rebasing the branch - since I had the same rebasing loop issue as my Typography QA branch :( I will be away for grad program workshop the next two days, if there's any urgent issue let me know via Teams and I'll try to get to them as soon as I can

**Comment by MitchAnderson93** [comment]
Best to start a fresh branch with the minor changes applied (github can't rebase due to merge conflicts)

**Pull request closed without merging**
