### PR TITLE
Qoloe 265 design qa on checkbox component

### PR DESCRIPTION
**Pull request by SenChung**
QOLOE 265 CSS changes

### CODE REVIEW

**Review by MitchAnderson93 — COMMENTED** [review]
Can you resolve merge conflict

**Comment by duttonw** [comment]
Can you also include the ability for handlebars (with correct json) to have the selectbox value have said item 'selected'
https://github.com/qld-gov-au/qgds-bootstrap5/blob/develop/src/components/bs5/formcheck/formcheck.hbs#L17

most likely in primary json
https://github.com/qld-gov-au/qgds-bootstrap5/blob/develop/src/components/bs5/formcheck/stories/checkbox/checkbox.data.json#L4
a new key "value" which is used to do said selection. This pattern could be used on all form inputs also.

see: 
https://github.com/spring-projects/spring-framework/blob/main/spring-webmvc/src/main/resources/org/springframework/web/servlet/view/freemarker/spring.ftl#L343

**Review by MitchAnderson93 — APPROVED** [review]
Approved with an assumption this is tested to resolve a UAT issue

**Comment by duttonw** [comment]
@SenChung we have a merge conflict.
@jortronQGov is this good with you also?

**Pull request closed without merging**
